# -*- coding: utf-8 -*-
"""Retail sale analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1INxgX5gTdTf3KzE38nmx4cg6gjZC83gw
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import seaborn as sns

# Load the dataset
data = pd.read_csv("/content/Wholesale customers data.csv")

data

from matplotlib import pyplot as plt
_df_3['Fresh'].plot(kind='hist', bins=20, title='Fresh')
plt.gca().spines[['top', 'right',]].set_visible(False)

# Display the first few rows of the dataset
print(data.head())

# Check for missing values
print(data.isna().sum())

# Get basic statistics for numerical columns
print(data.describe())

# Handling missing values by imputing with the mean
data.fillna(data.mean(), inplace=True)

# Box plot to visualize outliers in a numerical column
plt.boxplot(data['Fresh'])
plt.title('Box Plot of Fresh')
plt.show()

# Select relevant columns for clustering (e.g., Fresh, Milk, Grocery, etc.)
features = data[['Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper', 'Delicassen']]

# Define the number of clusters
kmeans = KMeans(n_clusters=3)

# Fit the model to the data
kmeans.fit(features)

# Get cluster labels for each customer
data['Cluster'] = kmeans.labels_

# Plot clusters
plt.scatter(data['Fresh'], data['Milk'], c=data['Cluster'], cmap='rainbow')
plt.xlabel('Fresh')
plt.ylabel('Milk')
plt.title('Customer Segmentation')
plt.show()

# Scatter plot using Seaborn
sns.scatterplot(x='Fresh', y='Milk', hue='Cluster', data=data)
plt.title('Customer Segmentation')
plt.xlabel('Fresh')
plt.ylabel('Milk')
plt.show()

